/**
 * Best-effort glyphs for the New Order service picker. We can't ship every
 * upstream's brand SVG, so well-known services get an emoji and everything else
 * falls back to a coloured letter badge.
 */
const EMOJI: Record<string, string> = {
  whatsapp: '💬',
  telegram: '✈️',
  'telegram business': '✈️',
  viber: '🟣',
  signal: '🔵',
  wechat: '💚',
  line: '💚',
  kakaotalk: '💛',
  michat: '💬',
  imo: '💬',
  botim: '💬',
  zalo: '🔷',
  discord: '🎮',
  slack: '💼',
  instagram: '📸',
  'instagram / threads': '📸',
  threads: '🧵',
  facebook: '📘',
  'tiktok / douyin': '🎵',
  tiktok: '🎵',
  douyin: '🎵',
  snapchat: '👻',
  twitter: '🐦',
  x: '✖️',
  'x (twitter)': '✖️',
  reddit: '🤖',
  linkedin: '💼',
  pinterest: '📌',
  tumblr: '📱',
  weibo: '🔴',
  vk: '🔵',
  clubhouse: '🎙️',
  bumble: '🐝',
  tinder: '🔥',
  badoo: '💜',
  hinge: '💗',
  okcupid: '💘',
  grindr: '🟡',
  'plenty of fish (pof)': '🐟',
  google: '🔍',
  'google / youtube / gmail': '🔍',
  youtube: '▶️',
  gmail: '📧',
  'proton / protonmail': '🔒',
  protonmail: '🔒',
  'mail.ru': '📬',
  yahoo: '💜',
  yandex: '🔴',
  'yandex / uber': '🔴',
  microsoft: '🪟',
  apple: '🍎',
  amazon: '📦',
  netflix: '🎬',
  spotify: '🎧',
  'openai (chatgpt)': '🤖',
  openai: '🤖',
  chatgpt: '🤖',
  claude: '🧠',
  poe: '🅿️',
  paypal: '💰',
  revolut: '💳',
  wise: '💸',
  payoneer: '💳',
  skrill: '💳',
  neteller: '💳',
  cashapp: '💵',
  venmo: '💸',
  'coinbase': '🪙',
  binance: '🟡',
  bybit: '🟡',
  okx: '⬛',
  kraken: '🐙',
  bitget: '🟦',
  kucoin: '🟩',
  crypto: '🪙',
  uber: '🚗',
  bolt: '⚡',
  lyft: '🚙',
  grab: '🟢',
  gojek: '🟢',
  indrive: '🟩',
  didi: '🟠',
  careem: '🟢',
  shopee: '🛍️',
  lazada: '🛒',
  tokopedia: '🟢',
  aliexpress: '🛒',
  alibaba: '🟠',
  temu: '🟠',
  wildberries: '🟣',
  ozon: '🔵',
  amazonfresh: '🥬',
  wolt: '🔵',
  glovo: '🟡',
  deliveroo: '🦌',
  doordash: '🚪',
  ubereats: '🍔',
  airbnb: '🏠',
  booking: '🏨',
  'booking.com': '🏨',
  steam: '🎮',
  roblox: '🟥',
  'epic games': '🎮',
  epicgames: '🎮',
  'battle.net': '⚔️',
  blizzard: '❄️',
  ncsoft: '🎮',
  xbox: '🎮',
  playstation: '🎮',
  nintendo: '🔴',
  twitch: '🟪',
  ebay: '🏷️',
  walmart: '🔵',
  target: '🎯',
  costco: '🔴',
  ikea: '🟡',
  nike: '✔️',
  adidas: '⚫',
  zara: '⬛',
  'truth social': '🇺🇸',
  truthsocial: '🇺🇸',
  truecaller: '📞',
  whatnot: '📦',
  vinted: '👗',
  depop: '🛍️',
  paxful: '🪙',
  payeer: '💳',
  qiwi: '🥝',
  webmoney: '💠',
  advcash: '💳',
  perfectmoney: '💵',
  tinkoff: '🟡',
  sberbank: '🟢',
  monzo: '🔴',
  n26: '⬜',
  chime: '💚',
  nubank: '🟣',
  mercadolibre: '🟡',
  mercadopago: '🔵',
  rappi: '🟠',
  ifood: '🔴',
  pagseguro: '🟡',
  picpay: '💚',
  'apple pay': '',
  applepay: '',
  'google pay': '',
  googlepay: '',
  linktr: '🌳',
  linktree: '🌳',
  patreon: '🧡',
  onlyfans: '💙',
  fansly: '💜',
  substack: '📰',
  medium: '⬛',
  notion: '⬛',
  figma: '🎨',
  canva: '🎨',
  dropbox: '📦',
  'google drive': '📁',
  mega: '🔴',
  icq: '🟢',
  skype: '🔵',
  zoom: '🎥',
  teams: '🟣',
  'microsoft teams': '🟣',
  webex: '🟢',
  hily: '💗',
  lovoo: '💘',
  mamba: '💋',
  kwai: '🎬',
  bigo: '📹',
  'bigo live': '📹',
  likee: '❤️',
  imvu: '🎭',
  yalla: '🟡',
  soulapp: '🌙',
  litmatch: '💛',
  yubo: '🟡',
  monkey: '🐒',
  azar: '🔵',
  omegle: '💬',
  'random chat': '💬',
};

/** Deterministic pastel for the letter-badge fallback. */
function badgeColor(seed: string): string {
  let h = 0;
  for (const ch of seed) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  return `hsl(${h % 360} 55% 42%)`;
}

export function serviceIcon(name: string): React.ReactNode {
  const key = name.trim().toLowerCase();
  const emoji = EMOJI[key];
  if (emoji) return <span className="text-sm leading-none">{emoji}</span>;
  const letter = (name.trim()[0] ?? '?').toUpperCase();
  return (
    <span
      className="inline-flex h-4 w-4 items-center justify-center rounded-[5px] text-[9px] font-bold text-white"
      style={{ background: badgeColor(key) }}
    >
      {letter}
    </span>
  );
}
